server:
  port: 9999
  servlet:
    context-path: /api
api:
  client:
    get-name:
      access-key: 7ae3ffba7425028cb67f771fcf4825f8
      secret-key: f8995877181ee0b8dc2b9e44a3768f91
    get-soup:
      access-key: 7ae3ffba7425028cb67f771fcf4825f8
      secret-key: f8995877181ee0b8dc2b9e44a3768f91
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/apihuoyouri
    username: root
    password: Aa123456
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0 